---
deployment:
  tasks:
    - export DEPLOYPATH=/home/xdsdw07tvnp4/entel-atencionempresas.com/
    - /usr/bin/rsync -av --exclude='index.php' public/ $DEPLOYPATH/
    - cp deploy/index.cpanel.php $DEPLOYPATH/index.php
